# Generated by Django 2.0.7 on 2018-07-18 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0006_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobiles.Company'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('audi', 'audi'), ('bmw', 'BMW'), ('volvo', 'volvo'), ('benz', 'benz')], default=('audi', 'audi'), max_length=16, unique=True),
        ),
    ]
