# Generated by Django 2.0.7 on 2018-07-18 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0007_auto_20180718_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carname',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.ForeignKey(choices=[('audi', 'audi'), ('bmw', 'BMW'), ('volvo', 'volvo'), ('benz', 'benz')], default=('audi', 'audi'), on_delete=django.db.models.deletion.CASCADE, to='automobiles.Company', unique=True),
        ),
    ]
