# Generated by Django 2.0.7 on 2018-07-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0008_auto_20180718_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('audi', 'audi'), ('bmw', 'BMW'), ('volvo', 'volvo'), ('benz', 'benz')], default=('audi', 'audi'), max_length=16, unique=True),
        ),
    ]
